### ISSUE TITLE
Some questions about the paper

### ISSUE THREAD

**Issue by guanjunwu** [Colmar-zlicheng/Spring-Gaus#2]
Hi, thanks for your great work!
I have some little questions about the paper:
1. It seems like anchor points $A$  are attached to initial 3D Gaussians?
2. How long does spring-gaus is trained on the real-world samples? It looks like the paper only present details on synthetic data.
3. what is registration network? As is shown in the paper, three viewpoints are insufficient for 3D Gaussians, it is related to sparse-view reconstruction and I think it also can be a interesting and difficult problem. How can you train the dynamic 3DGS/4DGS on the sparse-view input, can you provide more details?

Yours sincerely,
Guanjun

**Comment by Colmar-zlicheng** [comment]
Hi Guanjun, thank you for your issue.

1. Anchor points are independent from 3D Gaussians, we just compute anchor points' initial position from Gaussian kernels' centers.
2. Almost same to synthetic data.
3. We first use 50-100 images to train a static 3DGS, which has different position/rotation and shape with the initial state of 4DGS. So, we use a registration network to align static 3DGS and initial 4DGS.

Best wishes,
Licheng

**Comment by guanjunwu** [comment]
That sounds interesting!
Does it seem like if we have a well-trained 3D scene, 4D Gaussians can be trained with only 3 camera(sparse view) supervision?
