### ISSUE TITLE
How te get render views?

### ISSUE THREAD

**Issue by Boltzmachine** [Colmar-zlicheng/Spring-Gaus#5]
How do I get a rendered video as shown in the project page. I can only get 
![image](https://github.com/Colmar-zlicheng/Spring-Gaus/assets/56542320/f9e16895-f016-4ab0-bdcf-d0eebbc1298a)
by running the training script

**Comment by Colmar-zlicheng** [comment]
We just add a background (static image) to the video shown in the project page. You can add any background you like. The background we used is rendered via blender.

**Comment by Boltzmachine** [comment]
Thanks. What about the torus' texture?

**Comment by Colmar-zlicheng** [comment]
The texture is same as the demo in the project page.
