### ISSUE TITLE
The precise geometric structure of the Gaussians in the Static phase

### ISSUE THREAD

**Issue by X-Probiotics** [Colmar-zlicheng/Spring-Gaus#7]
In the **Static** phase of your project, an initial Gaussian is trained. I reviewed the point clouds of these Gaussians (for example, the hamburger), and I found their geometric structures to be remarkably precise, without any noise or artifacts. How did you achieve this?
My initial guess is that this is due to the fact that all camera poses in the training data are strictly calibrated, which prevents the Gaussians from developing any artifacts or ellipsoids outside their geometric structures. Do you think this hypothesis is correct? Or did you incorporate other operations to eliminate artifacts?

**Comment by X-Probiotics** [comment]
> In the **Static** phase of your project, an initial Gaussian is trained. I reviewed the point clouds of these Gaussians (for example, the hamburger), and I found their geometric structures to be remarkably precise, without any noise or artifacts. How did you achieve this? My initial guess is that this is due to the fact that all camera poses in the training data are strictly calibrated, which prevents the Gaussians from developing any artifacts or ellipsoids outside their geometric structures. Do you think this hypothesis is correct? Or did you incorporate other operations to eliminate artifacts?

![image](https://github.com/user-attachments/assets/5eb8b822-c9ca-4e6d-99b2-0f6761bb5311)

**Comment by Colmar-zlicheng** [comment]
Hi, for static reconstruction of real object, we have lots of camera views calibrated by colmap.
