### ISSUE TITLE
How to obtain rendered images of MPM simulation results with textures?

### ISSUE THREAD

**Issue by ReFantasy** [Colmar-zlicheng/Spring-Gaus#8]
Thanks for your work! We noticed that the provided synthetic dataset only contains point cloud files. We want to create our own dataset, but we don't know how to use Blender to render MPM simulated point cloud files, how to obtain and bind textures. Can you provide us with some references and suggestions?

**Comment by Colmar-zlicheng** [comment]
Hi, you can simply do surface reconstruction to obtain meshes from point cloud.

**Comment by ReFantasy** [comment]
> Hi, you can simply do surface reconstruction to obtain meshes from point cloud.

I am still confused. If we reconstruct and render the surface from a point cloud, how can we obtain its color and texture? Is it from the GS kernel? But the Gaussian kernel corresponds to the point cloud reconstructed from the original image, how to calculate the correspondence with the mesh?

**Comment by Colmar-zlicheng** [comment]
During surface reconstruction, you can also compute vertices' color for mesh (such as use the nearest point's color) to get a .ply file. GS was not used when generating the data.

**Comment by ReFantasy** [comment]
Assuming I have a mesh based model at the beginning, I perform volume sampling on it to obtain particles, and then use particles for MPM simulation. At each time step, I can reconstruct a mesh from the deformed particles and obtain the color of the mesh from the particles. Therefore, when I perform volume sampling at the beginning, I must assign the color to each particle at the same time, such as obtaining it from the texture image corresponding to this particle. Is my understanding correct?

**Comment by Colmar-zlicheng** [comment]
Yes, that's right.
